### ISSUE TITLE
Documentation of css-vars

### ISSUE THREAD

**Issue by Kolobok12309** [vue-styleguidist/vue-styleguidist#1480]
**The problem**

Some components can use css-vars in their code. 
We use this approach in out components.

**Proposed solution**

At first sight it can has this properties.

```
interface CssVarDefinition {
  name: string;
  // Comment near usage
  description?: string;
  // Color, Px, or another
  type?: string;
  default?: string;
}
```

**Alternative solutions**

Alternatively JSDoc syntax for this variables

**Additional context**

Possible code example 

```css
.button {
  color: #fff;
  /**
   * Background color of your button
   * @type {color}
   * @default [#000]
   */
  background-color: var(--c-button-bg, #000);
}
```
