### ISSUE TITLE
`deep` selector does not work

### ISSUE THREAD

**Issue by susnux** [vue-styleguidist/vue-styleguidist#1591]
**Current behavior**

While the deprecated `::v-deep` selector works, the recommended (Vue 2.7) `:deep(...)` selector does not.
The style like
```scss
:deep(.child-class) {
    background-color: #000;
}
```
is compiled to

(.child-class) {
    background-color: #000;
}

**Expected behavior**
`:deep()` should be handled similar to `::v-deep`.
