### ISSUE TITLE
Highlight functional components in the StyleGuide

### ISSUE THREAD

**Issue by dflock** [vue-styleguidist/vue-styleguidist#601]
**The problem**

I would like to highlight functional components in the StyleGuide.

**Proposed solution**

- Add a class (maybe `.functional`?) to the sidebar entry, and the `h2.pageheader` for functional components
- Use this in the styleguide templates CSS to add a badge

**Alternative solutions**

You could just add the class, and let people style this in their own custom styleguide css.

**Additional context**

One option, that I threw together in 5 mins for this ticket, would look like this:

![image](https://user-images.githubusercontent.com/47756/66605226-801aae80-eb64-11e9-915f-2b2404b46479.png)

To get this screenshot, I used the browsers dev tools to add the `functional` class to the sidebar & component title elements:

```html
<li class="rsg--item-71 rsg--isChild-72 rsg--isSelected-74 functional"><a class="rsg--link-65" href="/#/Common?id=pageheader">PageHeader</a></li>
...
<h2 id="pageheader" class="rsg--heading-14 rsg--heading2-16 functional"><a href="/#/Common?id=pageheader" class="rsg--sectionName-12">PageHeader</a></h2>
```

this is the class I made:

```css
.functional {
    background-image: url('data:image/svg+xml;utf-8,<svg aria-hidden="true" focusable="false" data-prefix="far" data-icon="star" class="svg-inline--fa fa-star fa-w-18" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path fill="currentColor" d="M528.1 171.5L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6zM388.6 312.3l23.7 138.4L288 385.4l-124.3 65.3 23.7-138.4-100.6-98 139-20.2 62.2-126 62.2 126 139 20.2-100.6 98z"></path></svg>');
    background-repeat: no-repeat;
    background-position-x: right;
    background-size: 20px;
    color: #ccc;
}
```

Obviously, this is just a rough mockup, but hopefully it gets the idea across.
