### ISSUE TITLE
Better markup for component & JSDoc tags output, to allow better styling

### ISSUE THREAD

**Issue by dflock** [vue-styleguidist/vue-styleguidist#602]
**The problem**

Given this component comment with two JSDoc tags:

```js
/**
 * Display a configurable Empty State indicator
 * @author Duncan Lock <dlock@phemi.com>
 * @version 1.2.3
 */
```
... this is the current markup output in the styleguide:

```html
<div class="rsg--docs-28">
  <p class="rsg--para-51">Display a configurable Empty State indicator</p>
  <div>
    <p class="rsg--para-51">
      Author: Duncan Lock
      <a href="mailto:dlock@phemi.com" class="rsg--link-65">
        dlock@phemi.com
      </a>
    </p>
    <p class="rsg--para-51">Version: 1.2.3</p>
  </div>
</div>
```

There are no semantic classes on any of this, and the JSDoc tags have no structural markup - they're just text nodes. This makes changing the styling of this with CSS much more difficult than it could be.

**Proposed solution**

With a few changes to the markup, like this, adding appropriate semantic classes and adding `<span>`s to the JSDoc tag components:

```html
<div class="rsg--docs-28 component">
  <p class="rsg--para-51 component-comment">
    Display a configurable Empty State indicator
  </p>
  <div class="jsdoc-tags">
    <p class="rsg--para-51 jsdoc-tag">
      <span class="tag-name">Author:</span>{" "}
      <span class="tag-value">
        Duncan Lock
        <a href="mailto:dlock@phemi.com" class="rsg--link-65">
          dlock@phemi.com
        </a>
      </span>
    </p>
    <p class="rsg--para-51 jsdoc-tag">
      <span class="tag-name">Version:</span>{" "}
      <span class="tag-value">1.2.3</span>
    </p>
  </div>
</div>;
```

... would make styling these elements much easier. This would make it fairly easy to turn this:

![image](https://user-images.githubusercontent.com/47756/66681537-c84ed500-ec27-11e9-8b52-7fa8a1f5af16.png)

into this:

![image](https://user-images.githubusercontent.com/47756/66681551-cf75e300-ec27-11e9-8713-b0505b5ec9ce.png)

using only this CSS:

```css
.jsdoc-tag .tag-value {
    padding: 4px;
    background-color: #eee;
}
.component-comment {
    font-size: 120%;
    font-style: italic;
    font-family: serif;
}
.jsdoc-tag .tag-name {
    background: #929292;
    color: white;
    padding: 0.25em;
    padding: 4px;
}
.jsdoc-tag span {
    display: table-cell;
}
.jsdoc-tag {
    display: table-row;
    row-gap: 4px;
}
.jsdoc-tags {
    display: table;
    margin-bottom: 1rem;
}
```

This is just a quick 5 minute example - there are obviously lots of other things you could do, with a bit more time, once the markups allows.

**Alternative solutions**

I tried to do this with minimal changes to the existing markup output - but changing the markup further could make things more flexible and accessible/semantic. For example, using a [definition list](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl) for JSDoc tag is one possibility.
